language: node_js
node_js:
  - "7"
script:
  - npm run test
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: dist
  target_branch: develop
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
